-- InternLoom Talent Matching Backend
-- Consolidated PostgreSQL schema for submission and review.
-- The Alembic migrations in backend/alembic/versions/ are the executable source of truth.

CREATE TYPE role AS ENUM ('student', 'company', 'admin');
CREATE TYPE locationtype AS ENUM ('remote', 'hybrid', 'onsite');
CREATE TYPE listingstatus AS ENUM ('draft', 'active', 'closed');
CREATE TYPE closedreason AS ENUM ('manual', 'cap_reached');
CREATE TYPE skillkind AS ENUM ('required', 'preferred');
CREATE TYPE applicationstatus AS ENUM ('submitted', 'under_review', 'shortlisted', 'rejected', 'offer_extended', 'withdrawn');

CREATE TABLE audit_log (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id INTEGER,
    actor_role VARCHAR(20),
    action VARCHAR(20) NOT NULL,
    resource_type VARCHAR(50) NOT NULL,
    resource_id INTEGER,
    before JSONB,
    after JSONB,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE skills (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role role NOT NULL,
    is_email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    pending_email VARCHAR(255),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE companies (
    user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    company_name VARCHAR(255) NOT NULL,
    is_approved BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE email_verifications (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    email VARCHAR(255) NOT NULL,
    otp_code VARCHAR(6) NOT NULL,
    purpose VARCHAR(20) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE notifications (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    type VARCHAR(50) NOT NULL,
    message TEXT NOT NULL,
    resource_type VARCHAR(50),
    resource_id INTEGER,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE student_profiles (
    user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    name VARCHAR(150),
    college VARCHAR(200),
    branch VARCHAR(100),
    graduation_year INTEGER,
    cgpa NUMERIC(4, 2),
    github_url VARCHAR(300),
    linkedin_url VARCHAR(300),
    bio TEXT,
    resume_url VARCHAR(300)
);

CREATE TABLE listings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id INTEGER NOT NULL REFERENCES companies(user_id) ON DELETE CASCADE,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    stipend NUMERIC(10, 2),
    location locationtype NOT NULL DEFAULT 'remote',
    deadline TIMESTAMPTZ,
    target_branch VARCHAR(100),
    target_graduation_year INTEGER,
    max_applicants INTEGER NOT NULL CHECK (max_applicants > 0),
    applicant_count INTEGER NOT NULL DEFAULT 0,
    status listingstatus NOT NULL DEFAULT 'draft',
    closed_reason closedreason,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE student_skills (
    student_id INTEGER NOT NULL REFERENCES student_profiles(user_id) ON DELETE CASCADE,
    skill_id INTEGER NOT NULL REFERENCES skills(id) ON DELETE CASCADE,
    PRIMARY KEY (student_id, skill_id)
);

CREATE TABLE applications (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id INTEGER NOT NULL REFERENCES listings(id) ON DELETE CASCADE,
    student_id INTEGER NOT NULL REFERENCES student_profiles(user_id) ON DELETE CASCADE,
    status applicationstatus NOT NULL DEFAULT 'submitted',
    match_score_snapshot NUMERIC(5, 2),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_one_application_per_role UNIQUE (listing_id, student_id)
);

CREATE TABLE listing_skills (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id INTEGER NOT NULL REFERENCES listings(id) ON DELETE CASCADE,
    skill_id INTEGER NOT NULL REFERENCES skills(id) ON DELETE CASCADE,
    kind skillkind NOT NULL,
    CONSTRAINT uq_listing_skill_kind UNIQUE (listing_id, skill_id, kind)
);

CREATE INDEX ix_audit_actor ON audit_log(actor_role, created_at);
CREATE INDEX ix_audit_log_created_at ON audit_log(created_at);
CREATE INDEX ix_skills_name ON skills(name);
CREATE INDEX ix_users_email ON users(email);
CREATE INDEX ix_users_role ON users(role);
CREATE INDEX ix_email_verifications_user_id ON email_verifications(user_id);
CREATE INDEX ix_notifications_user_read ON notifications(user_id, is_read);
CREATE INDEX ix_student_profiles_branch ON student_profiles(branch);
CREATE INDEX ix_student_profiles_graduation_year ON student_profiles(graduation_year);
CREATE INDEX ix_listings_company_id ON listings(company_id);
CREATE INDEX ix_listings_status ON listings(status);
CREATE INDEX ix_listings_status_created ON listings(status, created_at);
CREATE INDEX ix_listings_target_branch ON listings(target_branch);
CREATE INDEX ix_listings_target_graduation_year ON listings(target_graduation_year);
CREATE INDEX ix_applications_listing_status ON applications(listing_id, status);
CREATE INDEX ix_applications_student_id ON applications(student_id);
CREATE INDEX ix_listing_skills_listing ON listing_skills(listing_id);
